name: Deploy to Prod
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_KEY }}
          aws-region: us-east-1
      - run: |
          # Package app
          zip -r deploy.zip . -x '*.git*'
          # Upload to S3
          aws s3 cp deploy.zip s3://${{ vars.PROD_S3_BUCKET }}/deploy.zip
          # Trigger deployment
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name user-service-prod-asg \
            --preferences '{"InstanceWarmup":300,"MinHealthyPercentage":90}'
